### ISSUE TITLE
mess with essential members

### ISSUE THREAD

**Issue by romeor** [NagiosEnterprises/nagiosbpi#3]
When essential member is selected and Critical Threshold set to 0, parent group goes warning, when essential member is at critical.

Selecting Warning Threshold to 2 and having only one member (which is essential) down still sets the parent group state to warning. Removing the essential member option from affected member in this case makes the parent group OK.

In both cases the essential member is a host, if it matters.

**Comment by hedenface** [comment]
I'm closing this since the issue might have been resolved downstream. We'll be pushing those changes back upstream shortly (~2 Months?)!
